### ISSUE TITLE
Score is different in C++ inference compared to python.

### ISSUE THREAD

**Issue by rahulr95** [finnickniu/tensorflow_object_detection_tflite#3]
@finnickniu  I retrained an SSD Mobilenet model and converted it to tflite. I'm able to get accurate detections using the python code however while inferencing with C++ code, the score seems to be incorrect and therefore I'm getting a lot of false detections. Also the score seems to be always 0.9995. 
In the python code the score is taken from the 3rd output tensor, but in the C++ code it is extracted by calling the expit function with nums[count] as argument. Why is this so ?

Also, I'm only trying to detect one class. 

A quick reply will be really appreciated as I'm in a race against time. Thanks

**Comment by finnickniu** [comment]
Yes,  I had met this problem before as well. The only advice I can provide for you is to use quantized Mobilenetv2-ssd. The other mobilenet ssd still doesn’t support for c++ tflite operators. Hope this will help you.

**Comment by finnickniu** [comment]
NO RESPONSE
